name: release-please

on:
  workflow_dispatch: # allows to trigger the workflow manually from the Actions tab in GitHub
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: python
